Removed unnecessary wording from reliable core info
ataylorme/WordPress-Hosting-Best-Practices-Documentation pull request #29
Opened 2018-05-15 22:40 UTC by danieltj27

I've removed the part about having one theme active at a time because this doesn't feel like it's relevant information here. Whilst it is correct, it doesn't really matter what state plugins and themes are in (active/deactive) as it makes no difference in a backup containing only files.

2018-05-15 22:46 UTC, danieltj27 commented
I also update the version control section to make it easier to read.

2018-05-21 19:05 UTC, ataylorme requested changes
@danieltj27 thank you for the update/suggestions! We've done some work on Reliability since the PR so I resolved the merge conflicts and made a few comments. I think with a few adjustments the update to version control will be a good one.

2018-05-21 19:05 UTC, ataylorme commented on reliability/reliability.md
> +Version control is a way of tracking the changes made to files over time, especially for sites running WordPress for example. It allows users to track the revision history of code and to revert or ap
> Version control is a way of tracking the changes made to files over time, especially for sites running WordPress for example.

The end of this doesn't quite sound right to me. Version control is great for all kinds of things, beyond websites and WordPress. Maybe we can mention it is a best practice when working with files, such as code, that change over time.

2018-05-21 19:05 UTC, ataylorme commented on reliability/reliability.md
> +Version control is a way of tracking the changes made to files over time, especially for sites running WordPress for example. It allows users to track the revision history of code and to revert or ap
> if something goes wrong as you can quickly restore to a previous version very quickly without doing a full backup. 

I interpret "doing a full backup" as creating a backup, not restoring one.

Should this be something like "if something goes wrong as you can quickly restore to a previous state of the site code without restoring a full backup. "?

2018-05-21 21:20 UTC, danieltj27 commented
@ataylorme no problem. I've pushed my new changes based on your suggestions.

2018-05-21 21:28 UTC, ataylorme approved these changes
Looks good, thank you @danieltj27!

2018-05-21 21:29 UTC, merged

2018-05-21 21:32 UTC, ataylorme commented
The version control section has been updated on the [reliability handbook page](https://make.wordpress.org/hosting/handbook/handbook/reliability/)