First pass at recommended server environment doc
ataylorme/WordPress-Hosting-Best-Practices-Documentation pull request #6
Opened 2017-06-15 14:42 UTC by ataylorme

2017-06-28 17:05 UTC, getsource requested changes
Looks good, but have a few comments/small corrections

2017-06-28 17:05 UTC, getsource commented on server-environment/server-environment.md
> +PHP `7.0` or greater is highly encouraged but WordPress will run, with slower performance, on PHP `5.6` as well. For this reason PHP versions less than `5.6` are not recommended. See [WordPress and P
Do you mean that less than 7.0 are not recommended?

2017-06-28 17:05 UTC, getsource commented on server-environment/server-environment.md
> +WordPress core makes use of PHP extensions. If they the preferred extension is missing WordPress will either have to do more work to do the task the module helps with or, in the worst case, will remo
If ~~they~~ the preferred extension ...

2017-06-28 17:05 UTC, getsource commented on server-environment/server-environment.md
> +WordPress core makes use of PHP extensions. If they the preferred extension is missing WordPress will either have to do more work to do the task the module helps with or, in the worst case, will remo
Might be worthwhile to explain how WordPress attempts to gracefully degrade functionality, but this works.

2017-06-28 17:05 UTC, getsource commented on server-environment/server-environment.md
> +* filter - Used for securely filtering user input
What happens when extensions like this one are missing?  Might be good to have context, although for further context, I'm fine with it being in a future revision (and approving this review).

2017-06-28 17:05 UTC, getsource commented on server-environment/server-environment.md
> +* imagick - Provides better image quality for media uploads. See [WP_Image_Editor is incoming!](https://make.wordpress.org/core/2012/12/06/wp_image_editor-is-incoming/) for details.
Two more things, too: Smarter image resizing (for smaller images) and PDF thumbnail support, when GS is also available. Digging up these articles to add to the list.

2017-06-28 17:05 UTC, getsource commented on server-environment/server-environment.md
> +* Image Magic - Gets called by imagick
ImageMagick - Required by Imagick extension

2017-06-28 17:05 UTC, getsource commented on server-environment/server-environment.md
> +* Ghost Script - Provides a PDF thumbnail in the media library. See [Enhanced PDF Support in WordPress 4.7](https://make.wordpress.org/core/2016/11/15/enhanced-pdf-support-4-7/) for details.
Ghostscript - Enables Imagick/ImageMagick to generate PDF thumbnails for the media library.

2017-06-28 17:05 UTC, getsource commented on server-environment/server-environment.md
> +For the sake of completeness bleow is a list of the remaining PHP modules WordPress _may_ use in certain situations or if other modules are unavailable. These are fallbacks and not needed in an optim
add comma after "environment"

2017-06-28 17:14 UTC, ataylorme commented
@getsource posted updates based on your comments. Please review again when you can.

2017-09-06 17:19 UTC, ataylorme commented
@getsource can you review again? Your previous review with changes requested seems to be outdated but is still blocking merge.

2017-09-07 23:05 UTC, merged